### PR TITLE
Improve GitHub Action

### PR DESCRIPTION
**Pull request by wmutschl**
1. Factorize the workflow files as they only differ in the Dynare version.
2. Use official Dynare images from Docker Hub instead of my private registry.
3. Make badges in readme user independent, i.e. they'll work for forks of the repo as well.

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
@wmutschl Are the actions supposed to pass on the PR?

**Comment by wmutschl** [comment]
Yes they should have passed (and will when merged into master)! But I see that for pull requests I have to do things differently with passing the current commit to the container. I‘ll push an update to this PR tonight.

**Comment by wmutschl** [comment]
Now the checks fail, because:

> Anyone with collaborator access to this repository can use these secrets and variables for actions. They are not passed to workflows that are triggered by a pull request from a fork.
So I think it is easiest to simply disable running the CI for pull requests. However, it is running on my fork, so if the CI passes on https://github.com/wmutschl/DSGE_mod it is save to merge this.

**Comment by wmutschl** [comment]
Okay, this should be ready to be merged.

**Comment by wmutschl** [comment]
Yay! It passed!

**Pull request merged**
